In [2]:
from gensim.models import KeyedVectors
from numpy.ma.core import negative

model_path = './data/sgns.weibo.word'
model = KeyedVectors.load_word2vec_format(model_path)

In [3]:
print(model.vector_size)

300

In [4]:
print(model['地铁'])

[ 2.92064e-01 -5.18680e-02 -2.13720e-01  1.82131e-01  2.82900e-03
  4.14104e-01  1.56440e-01 -1.27940e-02 -3.28332e-01 -8.25000e-02
 -8.46890e-02 -2.14700e-02  1.18650e-01 -4.73659e-01 -1.97850e-02
  1.13939e-01  1.82734e-01 -6.46420e-02  5.60832e-01 -6.65230e-02
 -1.97960e-01  1.26039e-01 -3.28720e-01 -3.09730e-02 -3.46580e-01
 -1.53190e-01 -2.96226e-01 -5.75517e-01  1.10684e-01  8.19220e-02
 -1.04721e-01 -1.77477e-01 -1.21332e-01  1.49816e-01  2.86278e-01
 -8.11200e-03  6.72540e-02  6.92220e-02 -3.50973e-01 -5.49500e-02
 -7.80250e-02 -1.92952e-01 -1.70920e-01 -1.28289e-01  1.08204e-01
 -7.24913e-01 -1.11735e-01 -6.75000e-03  4.38086e-01 -8.75720e-02
 -1.41320e-01 -1.91726e-01  1.68363e-01 -7.85700e-02 -1.79772e-01
 -1.27950e-01  3.24675e-01  2.70616e-01  1.96330e-02 -3.09431e-01
 -4.02670e-02  5.80160e-02 -1.06603e-01  2.48022e-01  2.59204e-01
  2.16016e-01  3.96293e-01  2.48630e-02 -7.63330e-02  6.10183e-01
  2.73094e-01 -1.37777e-01  7.65180e-02 -1.35788e-01 -1.42440e-01
  1.22921e-01 -3.29422e-01  5.71580e-02  5.94921e-01 -5.50797e-01
  3.46176e-01 -2.69567e-01 -2.47488e-01  2.08690e-02  3.95993e-01
 -2.57373e-01  2.34584e-01  2.26339e-01 -4.64570e-01 -3.04508e-01
  1.36579e-01  2.80750e-01  1.50944e-01 -1.11040e-01  2.60098e-01
  6.91380e-02  5.03986e-01 -1.00347e-01 -6.18970e-02  1.35250e-01
  1.50892e-01 -4.07515e-01 -5.37930e-02  1.10587e-01 -9.04900e-02
  1.80515e-01 -3.51006e-01 -2.12241e-01  8.56400e-02 -1.51994e-01
  6.41400e-03 -9.84930e-02  4.62353e-01 -3.30745e-01  5.16491e-01
 -2.49457e-01 -1.81466e-01 -1.71039e-01 -2.64625e-01 -4.03930e-02
 -2.18122e-01  6.62730e-02  2.07282e-01 -2.42511e-01 -4.14579e-01
  1.92758e-01 -1.19829e-01  2.24573e-01 -3.92552e-01  3.18120e-02
 -4.93740e-02 -1.14619e-01 -3.98494e-01  3.01888e-01  1.38450e-02
 -2.05958e-01 -4.80272e-01  1.37910e-02 -4.25811e-01  1.17305e-01
  2.86182e-01  3.82148e-01  1.18033e-01 -1.16415e-01  1.14658e-01
 -3.49242e-01  2.36736e-01 -2.84652e-01  1.66909e-01 -1.47423e-01
  1.58550e-01  2.82934e-01  9.73860e-02  3.48558e-01  3.82375e-01
 -3.12930e-01  1.74523e-01  5.81934e-01  7.73360e-02 -7.09280e-02
 -1.00689e-01 -1.62409e-01 -8.50800e-03 -2.21862e-01 -2.81307e-01
 -6.17135e-01  3.29506e-01 -3.26858e-01  2.23377e-01 -1.77490e-01
  6.13310e-02 -1.77037e-01 -4.17570e-01  2.14060e-02 -1.34164e-01
  1.59830e-02  3.14000e-04  2.35130e-02 -4.57199e-01  1.02204e-01
  6.88330e-02  3.12781e-01 -2.39573e-01 -2.78332e-01  5.13939e-01
  3.16661e-01  3.60552e-01  9.18910e-02 -4.40668e-01 -4.06856e-01
 -2.39082e-01 -2.86843e-01 -1.29918e-01  2.75585e-01 -1.57855e-01
 -1.87841e-01 -3.53225e-01  1.68110e-02 -8.78310e-02 -2.54483e-01
  3.56101e-01  3.71631e-01 -4.13971e-01 -4.35651e-01 -1.00439e-01
 -4.12524e-01 -1.04495e-01  3.54830e-02 -1.74948e-01  5.01390e-02
 -1.17752e-01  3.58114e-01  9.76080e-02 -1.13460e-02 -6.86479e-01
  3.08385e-01  1.68549e-01 -3.57394e-01  7.42420e-02 -1.04000e-01
  8.36070e-02  2.79918e-01  2.05668e-01 -1.91806e-01  1.96990e-02
 -2.69668e-01  3.40448e-01  2.00093e-01 -6.15480e-02 -3.90508e-01
  2.49859e-01  1.13920e-02 -3.55860e-02 -9.75990e-02  6.83085e-01
  6.64080e-02  7.62330e-02  2.89197e-01  3.84086e-01  3.46560e-02
  3.09348e-01 -2.91596e-01  2.67043e-01 -2.67509e-01  3.15030e-01
 -3.91789e-01 -4.36780e-02 -8.02206e-01 -4.06730e-02  5.98826e-01
  2.11899e-01  1.04722e-01  5.96274e-01 -2.85005e-01  2.04500e-01
 -3.38460e-02  2.95850e-02  4.97640e-02  1.32707e-01 -3.10449e-01
 -1.01585e-01 -2.00878e-01 -1.95770e-02  7.63370e-02  1.93875e-01
 -1.06530e-01  2.16328e-01 -2.74200e-03 -6.12151e-01 -7.38670e-02
 -2.58649e-01 -8.32630e-02 -6.42669e-01  3.29758e-01 -3.20069e-01
 -1.32833e-01  1.36359e-01  1.37499e-01 -2.18507e-01 -3.72038e-01
  2.84177e-01 -2.69149e-01 -5.65299e-01  1.95994e-01 -3.25358e-01
  4.13170e-02 -2.43307e-01  5.54410e-02  1.01901e-01  8.98090e-02
  4.24190e-02 -3.56706e-01  5.22940e-02 -8.37000e-02 -2.83204e-01
 -1.03482e-01 -5.58960e-02  3.54650e-02  1.66978e-01  5.40452e-01]

In [6]:
similarity = model.similarity('地铁', '公交')
print('地铁 vs 公交 相似度：', similarity)

地铁 vs 公交 相似度： 0.65458214

In [8]:
len(model.index_to_key)

195202

In [10]:
model.similarity('地铁', '太阳')

np.float32(0.09804901)

In [12]:
model.most_similar(positive=['男人', '女孩'], negative=['男孩'], topn = 5)

[('女人', 0.6578881740570068),
 ('女孩子', 0.515068531036377),
 ('女生', 0.45194485783576965),
 ('女人真', 0.4420627951622009),
 ('女人们', 0.43698593974113464)]

## 训练自己的词向量

In [13]:
from gensim.models import Word2Vec

sentences = [
    ["我", "喜欢", "机器学习"],
    ["我", "喜欢", "深度学习"],
    ["机器学习", "很", "有趣"],
    ["深度学习", "很", "有趣"],
    ["量子计算"]   # 只出现一次
]

In [14]:
model = Word2Vec(
    sentences,          # 已分词的句子序列
    vector_size=100,    # 词向量维度
    window=5,           # 上下文窗口大小
    min_count=2,        # 最小词频（低于将被忽略）
    sg=1,               # 1: Skip-Gram, 0: CBOW
    workers=4           # 并行训练线程数
)

In [ ]:
# (3) 保存词向量
model.wv.save_word2vec_format('my_vectors.kv')

In [20]:
import pandas as pd
import jieba
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

In [3]:
df = pd.read_csv('./data/online_shopping_10_cats.csv')

In [4]:
df.head()

  cat  label                                             review
0  书籍      1  做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1  书籍      1  作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2  书籍      1  作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3  书籍      1  作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4  书籍      1  作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...

In [5]:
df['review']

0        做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1        作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2        作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3        作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4        作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...
                               ...
62769    我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
62770    房间很小，整体设施老化，和四星的差距很大。毛巾太破旧了。早餐很简陋。房间隔音很差，隔两间房间...
62771                        我感觉不行。。。性价比很差。不知道是银川都这样还是怎么的！
62772    房间时间长，进去有点异味！服务员是不是不够用啊！我在一楼找了半个小时以上才找到自己房间，想找...
62773    老人小孩一大家族聚会，选在吴宫泛太平洋，以为新加坡品牌一定很不错，没想到11点30分到前台，...
Name: review, Length: 62774, dtype: object

In [6]:
df[df['review'].isna()]

       cat  label review
36425  热水器      1    NaN

In [7]:
df = pd.read_csv('./data/online_shopping_10_cats.csv').dropna()

In [8]:
df['review']

0        做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1        作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2        作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3        作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4        作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...
                               ...
62769    我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
62770    房间很小，整体设施老化，和四星的差距很大。毛巾太破旧了。早餐很简陋。房间隔音很差，隔两间房间...
62771                        我感觉不行。。。性价比很差。不知道是银川都这样还是怎么的！
62772    房间时间长，进去有点异味！服务员是不是不够用啊！我在一楼找了半个小时以上才找到自己房间，想找...
62773    老人小孩一大家族聚会，选在吴宫泛太平洋，以为新加坡品牌一定很不错，没想到11点30分到前台，...
Name: review, Length: 62773, dtype: object

In [16]:
sentences = [[token for token in jieba.lcut(sentence) if token.strip() != '']  for sentence in df['review']]

In [17]:
sentences[0:3]

[['做',
  '父母',
  '一定',
  '要',
  '有',
  '刘墉',
  '这样',
  '的',
  '心态',
  '，',
  '不断',
  '地',
  '学习',
  '，',
  '不断',
  '地',
  '进步',
  '，',
  '不断',
  '地',
  '给',
  '自己',
  '补充',
  '新鲜血液',
  '，',
  '让',
  '自己',
  '保持',
  '一颗',
  '年轻',
  '的',
  '心',
  '。',
  '我',
  '想',
  '，',
  '这',
  '是',
  '他',
  '能',
  '很',
  '好',
  '的',
  '和',
  '孩子',
  '沟通',
  '的',
  '一个',
  '重要',
  '因素',
  '。',
  '读',
  '刘墉',
  '的',
  '文章',
  '，',
  '总能',
  '让',
  '我',
  '看到',
  '一个',
  '快乐',
  '的',
  '平易近人',
  '的',
  '父亲',
  '，',
  '他',
  '始终',
  '站',
  '在',
  '和',
  '孩子',
  '同样',
  '的',
  '高度',
  '，',
  '给',
  '孩子',
  '创造',
  '着',
  '一个',
  '充满',
  '爱',
  '和',
  '自由',
  '的',
  '生活',
  '环境',
  '。',
  '很',
  '喜欢',
  '刘墉',
  '在',
  '字里行间',
  '流露出',
  '的',
  '做',
  '父母',
  '的',
  '那种',
  '小',
  '狡黠',
  '，',
  '让',
  '人',
  '总是',
  '忍俊不禁',
  '，',
  '父母',
  '和',
  '子女',
  '之间',
  '有时候',
  '也',
  '是',
  '一种',
  '战斗',
  '，',
  '武力',
  '争斗',
  '过于',
  '低级',
  '了',
  '，',
  '智力',
  '较量',
  '才',
  '更',
  '有',
  '趣味',
  '。',
  '所以',
  '，',
  '做',
  '父母',
  '的',
  '得',
  '加把劲',
  '了',
  '，',
  '老',
  '思想',
  '老',
  '观念',
  '注定',
  '会',
  '一败涂地',
  '，',
  '生命不息',
  '，',
  '学习',
  '不止',
  '。',
  '家庭教育',
  '，',
  '真的',
  '是',
  '乐在其中',
  '。'],
 ['作者',
  '真有',
  '英国人',
  '严谨',
  '的',
  '风格',
  '，',
  '提出',
  '观点',
  '、',
  '进行',
  '论述',
  '论证',
  '，',
  '尽管',
  '本人',
  '对',
  '物理学',
  '了解',
  '不深',
  '，',
  '但是',
  '仍然',
  '能',
  '感受',
  '到',
  '真理',
  '的',
  '火花',
  '。',
  '整本书',
  '的',
  '结构',
  '颇',
  '有',
  '特点',
  '，',
  '从',
  '当时',
  '（',
  '本',
  '书写',
  '于',
  '八十年代',
  '）',
  '流行',
  '的',
  '计算机',
  '话题',
  '引入',
  '，',
  '再用',
  '数学',
  '、',
  '物理学',
  '、',
  '宇宙学',
  '做',
  '必要',
  '的',
  '铺垫',
  '—',
  '—',
  '这些',
  '内容',
  '占据',
  '了',
  '大部分',
  '篇幅',
  '，',
  '最后',
  '回到',
  '关键问题',
  '：',
  '电脑',
  '能',
  '不能',
  '代替',
  '人脑',
  '。',
  '和',
  '现在',
  '流行',
  '的',
  '观点',
  '相反',
  '，',
  '作者',
  '认为',
  '人',
  '的',
  '某种',
  '“',
  '洞察',
  '”',
  '是',
  '不能',
  '被',
  '算法',
  '模拟',
  '的',
  '。',
  '也许',
  '作者',
  '想',
  '说',
  '，',
  '人',
  '的',
  '灵魂',
  '是',
  '无可取代',
  '的',
  '。'],
 ['作者',
  '长篇大论',
  '借用',
  '详细',
  '报告',
  '数据处理',
  '工作',
  '和',
  '计算结果',
  '支持',
  '其新',
  '观点',
  '。',
  '为什么',
  '荷兰',
  '曾经',
  '县有',
  '欧洲',
  '最高',
  '的',
  '生产率',
  '？',
  '为什么',
  '在',
  '文化',
  '上',
  '有着',
  '深刻',
  '纽带',
  '关系',
  '的',
  '中国',
  '和',
  '日本',
  '却',
  '在',
  '经济',
  '发展',
  '上',
  '有着',
  '极大',
  '的',
  '差异',
  '？',
  '为什么',
  '英国',
  '的',
  '北美',
  '殖民地',
  '造就',
  '了',
  '经济',
  '强大',
  '的',
  '美国',
  '，',
  '而',
  '西班牙',
  '的',
  '北美',
  '殖民',
  '却',
  '造就',
  '了',
  '范后',
  '的',
  '墨西哥',
  '？',
  '…',
  '…',
  '很',
  '有',
  '价值',
  '，',
  '但',
  '不',
  '包括',
  '【',
  '中国',
  '近代史',
  '专业',
  '】',
  '。']]

In [18]:

model = Word2Vec(
    sentences,          # 已分词的句子序列
    vector_size=100,    # 词向量维度
    window=5,           # 上下文窗口大小
    min_count=2,        # 最小词频（低于将被忽略）
    sg=1,               # 1: Skip-Gram, 0: CBOW
    workers=4           # 并行训练线程数
)

In [14]:
model.wv['地铁']

array([ 0.25146398,  0.29204106,  0.08295906,  0.17511508, -0.08025803,
       -0.46069276,  0.29893175,  1.1612579 , -0.14168867,  0.05376106,
       -0.27059972, -0.1378845 , -0.2085184 , -0.02625815,  0.3567058 ,
       -0.38292658,  0.3888726 , -0.62884504,  0.3636912 , -0.09825888,
       -0.03981847, -0.13672003,  0.55010045,  0.46636367, -0.20146826,
       -0.46431118, -0.29440784,  0.18929431, -0.09700701, -0.2140558 ,
        0.22271983,  0.311678  , -0.49374074, -0.3608403 ,  0.10864531,
       -0.18163942,  0.11519855, -0.45058104, -0.02837364, -0.8765359 ,
       -0.0116253 ,  0.04321896,  0.32387212, -0.02356409, -0.17901559,
        0.40114182, -0.20931369, -0.06258011,  0.09363347, -0.20700167,
       -0.16223355, -0.1335011 , -0.6657899 , -0.7118181 , -0.1869058 ,
        0.30522224,  0.06110308,  0.5916828 , -0.14831387, -0.30542803,
        0.1028256 ,  0.2856858 , -0.04322176, -0.04662691, -0.11850881,
        0.49745268,  0.3782197 , -0.24479708, -0.44508117, -0.12219921,
       -0.4298685 ,  0.5628049 ,  0.3780709 ,  0.118247  ,  0.26065558,
       -0.19976394,  0.2705752 , -0.41231915, -0.321229  , -0.24160087,
       -0.15710868, -0.57661796,  0.17016782,  0.6990118 , -0.18478459,
       -0.3443794 , -0.22885603,  0.15512225,  0.17020069, -0.0056478 ,
       -0.52001643,  0.39145327,  0.17995913,  0.28946525,  0.7530567 ,
        0.46074605,  0.11721573, -0.01635811,  0.09349471, -0.34255487],
      dtype=float32)

In [22]:
model.wv.save_word2vec_format('./data/word2vec.txt')

In [23]:
KeyedVectors.load_word2vec_format('./data/word2vec.txt', binary=False)

# 第三节 词向量应用

## 步骤
1. 加载词向量
2. 处理OOV
3. 准备词向量矩阵
4. 创建embedding
5.

In [36]:
import torch
import torch.nn as nn
from gensim.models import KeyedVectors
import numpy as np

In [25]:
wv = KeyedVectors.load_word2vec_format('./data/word2vec.txt', binary=False)

In [41]:
unk_token = '<unk>'
index2word = [unk_token] + wv.index_to_key
word2index = {word: index for index, word in enumerate(index2word)}

In [26]:
wv.vector_size

100

In [27]:
len(wv.index_to_key)

34576

In [34]:
print(wv)

KeyedVectors<vector_size=100, 34576 keys>

In [35]:
num_embeddings = len(index2word)
embedding_dim = wv.vector_size
embedding_matrix = torch.randn(num_embeddings, embedding_dim)

for index, token in enumerate(index2word):
    if token in wv:
        embedding_matrix[index] = torch.tensor(wv[token])
# 把存在电脑上的wv持久化的文件读到内存里，第一行作为unknown的token，其他部分照搬，然后得到的embedding_matrix就是第一行是<unk>:vector[1x100] 其余还是预训练的数据

In [38]:
embedding = nn.Embedding.from_pretrained(embedding_matrix)
embedding

Embedding(34576, 100)

In [39]:
text = "我喜欢乘坐地铁"
tokens = jieba.lcut(text)
input_ids = [wv.key_to_index[token] for token in tokens] # 没有处理OOV
input_tensor = torch.tensor(input_ids)
embedding(input_tensor)

tensor([[ 0.2986,  0.1158,  0.1555,  0.2226,  0.0911, -0.8412,  0.3645, -0.0711,
          0.0324,  0.0730,  0.1488, -0.3440,  0.0472, -0.4379, -0.1110, -0.2409,
         -0.0320, -0.3949, -0.1085, -0.4997,  0.4487,  0.1236,  0.4678, -0.4605,
         -0.2762,  0.0197,  0.0331,  0.4818,  0.0248, -0.2162,  0.2693,  0.0513,
         -0.1355,  0.0636, -0.3086,  0.1452,  0.2266, -0.1203, -0.2510, -0.2985,
          0.0499, -0.1507,  0.0285,  0.1857,  0.0668,  0.1513, -0.0015, -0.0168,
          0.1378,  0.0353, -0.2122, -0.0188,  0.2813, -0.0204, -0.3760,  0.2712,
          0.2837, -0.1796, -0.1311,  0.2042,  0.4569, -0.2516, -0.6263, -0.3390,
         -0.3094,  0.4027,  0.1241,  0.5577, -0.4599, -0.2460, -0.0532, -0.2664,
          0.3569, -0.1914, -0.0896,  0.1583,  0.1769, -0.2683, -0.2399, -0.1127,
         -0.4451,  0.1720,  0.0353,  0.4994, -0.1527,  0.0377, -0.0865,  0.1678,
          0.2407, -0.0886, -0.0058, -0.1909, -0.2097,  0.3762,  0.2265, -0.1974,
         -0.1492,  0.0175, -0.1314, -0.3823],
        [-0.4296, -0.2127, -0.0935,  0.1364, -0.1316, -0.8474,  0.9728,  0.4571,
         -0.0191, -0.4286, -0.2369, -0.4265,  0.3470, -0.4250, -0.0250,  0.5040,
         -0.0408, -0.8408, -0.6576, -0.1659,  0.2956, -0.3148,  0.7656, -0.2471,
         -0.3129, -0.4971, -0.3879, -0.3240, -0.0219, -0.3906, -0.2020, -0.4473,
         -0.3804, -0.5317, -0.4591,  0.0600,  0.2060, -0.0091,  0.0279,  0.1654,
          0.2444,  0.0830, -0.0226,  0.6037,  0.1822,  0.6161,  0.0271,  0.0448,
          0.2323,  0.3623,  0.0245, -0.2158,  0.4420, -0.5028, -0.2062,  0.4360,
          0.0059, -0.4796, -0.5399, -0.3285, -0.4631, -0.8719,  0.2402,  0.0877,
         -0.0172, -0.0956,  0.3195,  0.6618,  0.0358,  0.4946,  0.0772, -0.5313,
          1.0808, -0.0260,  0.0698, -0.1519, -0.0342, -0.0770,  0.0808, -0.0203,
         -0.1980, -0.0113,  0.3136,  0.0890,  0.3261, -0.0653, -0.2794, -0.1309,
          0.2384,  0.2106,  0.6807,  0.1583,  0.1950, -0.3909,  0.4131,  0.2087,
          0.3071,  0.4881,  0.1531, -0.6242],
        [-0.0190,  0.1998,  0.1214,  0.1124,  0.2950, -0.4179,  0.1630,  0.3212,
         -0.2705, -0.1887,  0.0768, -0.2682,  0.0695,  0.0681,  0.0337, -0.1381,
          0.1950, -0.3830,  0.0594, -0.2385,  0.3537, -0.0962,  0.0598, -0.1657,
         -0.0513,  0.1068, -0.0649,  0.0590,  0.0964,  0.0911, -0.0546, -0.1274,
         -0.2816, -0.0498,  0.1664, -0.0343,  0.2054,  0.1118, -0.0496, -0.3541,
         -0.2319, -0.1412, -0.1940, -0.1132,  0.3560, -0.0664,  0.1326,  0.1306,
         -0.0190,  0.1659, -0.0998, -0.0086,  0.0141, -0.0623,  0.2591, -0.1028,
          0.0559,  0.0642, -0.2766,  0.0125,  0.1404,  0.1988,  0.1005, -0.0549,
         -0.0288,  0.1284,  0.1024,  0.3261,  0.2860,  0.4367,  0.0275, -0.1413,
          0.0129,  0.1222, -0.0063,  0.1884,  0.1396,  0.1078, -0.2984, -0.1823,
         -0.0352,  0.1961, -0.1847,  0.2235,  0.0435,  0.2293,  0.3480,  0.1512,
          0.3409,  0.1768,  0.2914, -0.3390,  0.1749,  0.3070,  0.3358,  0.4362,
          0.3609, -0.4312,  0.3043, -0.2976],
        [ 0.0189,  0.3346, -0.0356,  0.1630,  0.1403, -0.3869,  0.4665,  0.8106,
         -0.3772,  0.0724, -0.0498, -0.1840,  0.2125, -0.0314,  0.4074, -0.1652,
          0.4420, -0.2811, -0.2162,  0.0686,  0.4470, -0.3037,  0.1910, -0.3212,
         -0.2913,  0.2727,  0.0866,  0.4775,  0.2028,  0.0708, -0.1998,  0.0899,
         -0.3105, -0.3485,  0.4523, -0.1408,  0.1556,  0.1492,  0.1689, -0.5060,
         -0.5135,  0.0700, -0.2656, -0.0488,  0.7569, -0.3141, -0.0287,  0.4600,
          0.1394,  0.1820, -0.0160,  0.1694, -0.1333,  0.0720,  0.3010,  0.0615,
          0.2645,  0.2089, -0.4054, -0.2368,  0.0943,  0.6000, -0.0964,  0.0393,
          0.0442,  0.6676,  0.2057,  0.8573,  0.4769,  0.4287,  0.1053, -0.0881,
          0.0653,  0.4931, -0.0979,  0.3307, -0.0154,  0.1635, -0.3597, -0.8998,
          0.2134, -0.0795, -0.1594, -0.0057,  0.2616,  0.2879,  0.6377,  0.1500,
          0.3167,  0.3530,  0.4028, -0.7300,  0.1359,  0.4576,  0.3009,  0.6350,
          0.3437, -0.8730,  0.4104, -0.1957]])

In [42]:
text = "我喜欢乘坐地铁"
tokens = jieba.lcut(text)
input_ids = [word2index.get(token, word2index[unk_token]) for token in tokens]
input_tensor = torch.tensor(input_ids)
embedding(input_tensor)

tensor([[-3.4813e-01,  1.0072e-01,  3.2521e-01, -3.4149e-01, -3.3096e-02,
         -4.7691e-01,  5.5949e-01,  3.8537e-01, -2.1289e-01,  3.2176e-01,
         -1.1068e-01, -2.1118e-01, -1.3260e-02, -9.4665e-02,  5.4965e-02,
         -1.8843e-01,  2.0984e-01, -1.9970e-01, -3.4867e-01, -1.6420e-01,
         -5.1776e-02,  2.8219e-02,  6.5568e-01, -1.7580e-01, -1.2367e-01,
          4.6072e-01, -3.5287e-02, -1.1235e-01, -1.1620e-01, -2.2572e-01,
          1.5255e-01, -2.6244e-01, -5.8755e-02, -2.4427e-01, -1.5130e-01,
          1.0394e-02,  2.7228e-01,  1.5155e-01,  4.0211e-01, -3.1396e-01,
         -1.4572e-01,  1.2839e-01, -2.2655e-01,  3.7954e-02, -7.9699e-03,
         -1.8070e-01, -2.7984e-01,  3.3744e-01,  1.3283e-01,  4.7475e-01,
         -8.6188e-02, -8.1918e-02,  2.6509e-01, -2.5803e-01, -1.4981e-02,
          3.9479e-01,  4.1536e-01, -1.0327e-01,  2.7353e-01, -4.5549e-02,
          3.7656e-01, -3.6514e-01,  8.6951e-03, -1.1146e-01,  5.1326e-02,
          6.5250e-01, -1.0866e-01,  4.9570e-01, -5.8273e-01,  1.4525e-01,
         -1.3067e-01, -6.0906e-02,  6.3596e-01,  9.5183e-02,  1.9339e-01,
          4.8663e-01,  1.4010e-01,  9.2806e-04, -2.3573e-01, -9.9241e-03,
         -2.5893e-01,  1.3525e-02,  7.1915e-02,  2.0364e-01, -4.0810e-01,
         -1.6783e-01, -8.3697e-02,  2.5593e-01,  3.6122e-02, -1.7105e-01,
          3.5782e-01,  1.8092e-01,  5.6018e-02,  2.0427e-01,  1.0290e-01,
         -8.9225e-03, -1.0161e-01,  1.9081e-02,  3.7784e-02, -1.5827e-01],
        [ 5.6587e-02, -1.6086e-01, -2.7606e-01, -2.8727e-01, -3.1070e-01,
         -1.0038e+00,  4.6192e-01,  5.1223e-01,  2.0436e-01,  5.6935e-02,
         -1.0378e-01, -8.6286e-02,  3.7599e-01, -2.1878e-01,  3.1308e-01,
         -5.8794e-02,  5.2896e-01,  2.0102e-02,  5.9027e-03, -1.6739e-01,
          3.5079e-02, -3.9888e-01,  2.8350e-01,  2.1483e-01, -4.2186e-01,
         -3.3279e-01, -2.1188e-01,  3.7863e-02, -6.4821e-01, -3.9795e-01,
          2.4300e-01, -5.0247e-03,  3.8892e-01, -5.9295e-01, -1.8499e-01,
          7.3426e-02,  5.7043e-02, -1.7056e-01,  2.2896e-01, -4.2451e-01,
         -1.8766e-01, -2.7076e-02,  2.1691e-01,  2.1149e-01,  2.1870e-01,
         -3.1569e-01, -9.4886e-02, -2.0283e-01,  2.2840e-01,  2.7035e-01,
         -6.1683e-02,  7.3725e-02,  3.2513e-01, -2.9257e-01, -1.1099e-01,
         -1.0729e-01, -3.5504e-01,  6.8626e-03,  2.3198e-01,  7.4079e-02,
          3.3783e-01, -4.9905e-01, -7.6152e-01, -4.0319e-02, -5.7054e-01,
          4.0980e-01, -3.0088e-01,  4.6962e-01, -9.9023e-02,  1.5857e-01,
         -2.4566e-02,  6.3645e-03,  5.5055e-01,  3.0711e-01,  3.2002e-01,
          1.9172e-02,  5.1807e-01,  2.2575e-01, -5.1605e-01, -4.8069e-01,
         -6.3307e-01,  8.2234e-01, -1.3224e-01,  1.9079e-01, -2.2057e-01,
         -1.3859e-01,  1.9455e-01,  1.6765e-01, -1.5536e-01, -9.7456e-02,
          2.0498e-01, -1.8138e-01,  2.9107e-01,  2.5241e-01,  3.6228e-01,
          3.5931e-02,  4.0503e-01,  4.2373e-02,  1.0519e-01, -2.7752e-01],
        [-3.2485e-02,  1.9768e-01, -2.6190e-01, -3.3160e-02,  1.5932e-02,
         -9.7780e-01,  2.9929e-01,  7.9390e-01, -3.3835e-01, -2.5663e-01,
          5.9339e-01, -6.2388e-01, -1.7140e-01,  5.7969e-01,  1.8765e-01,
          1.7272e-01,  4.2200e-03,  1.0118e-01, -2.3756e-02, -4.5184e-01,
          2.3073e-01,  2.8476e-01, -7.7693e-02, -1.2273e-01, -3.4121e-01,
          2.0290e-01, -2.8653e-01,  2.3819e-01, -2.3997e-01,  2.0203e-01,
          4.2479e-01, -2.4985e-02,  2.6394e-01, -2.0822e-01,  9.3015e-02,
          5.3940e-01, -1.4572e-03, -4.2900e-01,  1.6676e-01, -1.4837e-01,
          4.3584e-01, -5.4157e-01, -5.6361e-02, -2.3528e-01,  3.2698e-01,
         -2.6242e-02,  8.0396e-01, -1.5452e-01, -1.1688e-01,  1.5297e-01,
          1.5662e-01, -1.6030e-01,  3.8869e-01, -7.3592e-02,  8.1231e-02,
          2.9236e-01, -1.0455e-01,  5.7472e-02,  4.4977e-02,  2.0621e-01,
         -9.1066e-02,  1.8447e-01,  2.1423e-01, -1.3244e-01, -8.5961e-02,
          4.3059e-01,  6.1946e-02,  1.6410e-01, -8.7765e-02,  6.0066e-01,
         -3.0654e-01, -3.2506e-01,  2.1749e-01,  3.2143e-01,  9.7778e-01,
          1.3916e-01, -9.2327e-02,  1.4604e-01, -5.7626e-01,  1.6041e-01,
         -7.5654e-02,  6.8377e-01, -4.8859e-01,  7.6934e-01,  1.2631e-01,
          1.8015e-01, -1.0078e-01, -3.0022e-02,  5.6145e-01, -5.9006e-01,
          2.5867e-01, -1.0936e-01,  4.2806e-01,  1.7757e-01,  3.8628e-01,
          2.9823e-01,  2.1309e-01, -2.9751e-01, -1.2115e-01, -5.6263e-01],
        [-6.2602e-02,  4.4591e-01,  2.8512e-01, -1.0012e-01,  3.7661e-03,
         -3.5290e-01,  2.2377e-01,  1.1579e-01, -8.0188e-01,  2.4745e-01,
         -1.0851e-01, -8.8847e-01,  5.6515e-01, -2.1202e-01,  5.4969e-02,
         -2.4845e-02,  4.1390e-02, -1.7810e-02, -1.8308e-01, -4.0293e-01,
          4.4439e-01, -1.9354e-01,  5.2394e-01,  9.6868e-02, -1.6647e-01,
          4.2052e-02,  8.4828e-02,  1.7828e-01, -7.6837e-02, -5.6657e-01,
          4.1072e-01,  2.4544e-01, -3.0995e-02, -2.6908e-01, -1.6330e-01,
         -3.3887e-01,  1.8689e-01,  7.1730e-02, -1.5879e-01, -3.5487e-01,
         -9.0808e-02, -4.3815e-01,  1.0735e-01,  3.6134e-01,  1.3727e-01,
          2.7451e-02, -1.6937e-01,  5.5261e-01,  2.9608e-01,  3.1885e-01,
         -2.1170e-01,  2.0094e-01,  2.7267e-01, -6.1703e-02, -9.3746e-03,
          3.1840e-02,  2.1429e-02,  4.0704e-01, -5.9915e-01,  1.8153e-01,
          1.1945e-01,  7.6993e-02, -3.0111e-01, -5.2495e-01, -3.4371e-01,
          2.7528e-01, -2.8758e-01,  5.9674e-01,  4.4717e-02,  7.8352e-02,
          3.0842e-01,  2.8995e-01,  4.6615e-01, -2.7275e-01, -3.6204e-03,
          4.6689e-01, -4.0486e-01,  7.9430e-02, -3.5848e-01,  8.8144e-02,
         -4.8382e-01, -8.3137e-02,  2.9147e-01, -9.2146e-02, -2.8805e-01,
          1.9459e-01,  1.9752e-01,  1.5959e-01,  2.7058e-01, -1.9848e-01,
         -9.3547e-02, -1.9467e-01,  4.2569e-01, -8.0713e-02,  8.4032e-01,
         -6.0713e-02, -3.5209e-02, -3.0671e-01, -3.7735e-01,  2.2607e-01]])